# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sherlock < Formula
  desc "sherlock is a command line tool to interact with a datasherlocks cloud."
  homepage "https://datasherlocks.io/docs"
  version "0.0.12"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/datasherlocks/sherlock/releases/download/v0.0.12/sherlock_Darwin_arm64.tar.gz"
      sha256 "372944dca751b7dd87668def4e05deddbf67d04247c5ac0b421b7590f7227ad8"

      def install
        bin.install "sherlock"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/datasherlocks/sherlock/releases/download/v0.0.12/sherlock_Darwin_x86_64.tar.gz"
      sha256 "3e7022fcb07af7d69f09fb6a7720c64c291018f08b6a7513b77d7d45a007d550"

      def install
        bin.install "sherlock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datasherlocks/sherlock/releases/download/v0.0.12/sherlock_Linux_arm64.tar.gz"
      sha256 "717d1cf79b475d75c15281fdbff2b97aede201ca9713cb731b47fe28a53280dc"

      def install
        bin.install "sherlock"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/datasherlocks/sherlock/releases/download/v0.0.12/sherlock_Linux_x86_64.tar.gz"
      sha256 "2c01c2a521411e4f3f8c151b873a45fab274aa9cca5700ed0906ec5d72c147fd"

      def install
        bin.install "sherlock"
      end
    end
  end
end
