# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sherlock < Formula
  desc "sherlock is a command line tool to interact with a datasherlocks cloud."
  homepage "https://datasherlocks.io/docs"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/datasherlocks/datasherlocks/releases/download/v0.0.2/datasherlocks_Darwin_arm64.tar.gz"
      sha256 "bb7d5757f7232ddc452b77dca5692eaa8e4d313cfa1c2aace3fa7b5f947322c7"

      def install
        bin.install "sherlock"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/datasherlocks/datasherlocks/releases/download/v0.0.2/datasherlocks_Darwin_x86_64.tar.gz"
      sha256 "43eebbb7f67045736a24ab7eb9713d46cc29e86518be936843fd8c97a4443c97"

      def install
        bin.install "sherlock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datasherlocks/datasherlocks/releases/download/v0.0.2/datasherlocks_Linux_arm64.tar.gz"
      sha256 "f32ecf310b5b474163bfc8a548fa9646f8cb8b08a647cc95e446f08e0dcec6c4"

      def install
        bin.install "sherlock"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/datasherlocks/datasherlocks/releases/download/v0.0.2/datasherlocks_Linux_x86_64.tar.gz"
      sha256 "ef22d9f080f8c5ad756cf6cb73d016a2860497ab8b18d433f4c3a7bb0fba2c2d"

      def install
        bin.install "sherlock"
      end
    end
  end
end
