# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfstudio < Formula
  desc "Command-line interface for managing and interacting with The SaaS Company's cloud services, providing streamlined access to resources and operations."
  homepage "https://thesaas.company.io/docs"
  version "0.0.33"

  on_macos do
    on_intel do
      url "https://github.com/thesaas-company/cloud/releases/download/v0.0.33/cloud_Darwin_x86_64.tar.gz"
      sha256 "9674178077987a17021310d44dc3d46eba8aeaeca1c3a345402f1b8f3a6f30b6"

      def install
        bin.install "tfstudio"
      end
    end
    on_arm do
      url "https://github.com/thesaas-company/cloud/releases/download/v0.0.33/cloud_Darwin_arm64.tar.gz"
      sha256 "3eef4684f18c7c5e5c64e779b3c4c7773528f8bfeff0a162386fe1abd248adfb"

      def install
        bin.install "tfstudio"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thesaas-company/cloud/releases/download/v0.0.33/cloud_Linux_x86_64.tar.gz"
        sha256 "d8ecba05855de80f402fbc84a21c2b74db27b1386de5931284236ce665addc84"

        def install
          bin.install "tfstudio"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thesaas-company/cloud/releases/download/v0.0.33/cloud_Linux_arm64.tar.gz"
        sha256 "1491e66eef543b3a18b879f95330f3c61765164da25d4967c75e05565d611b64"

        def install
          bin.install "tfstudio"
        end
      end
    end
  end
end
