# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfstudio < Formula
  desc "Command-line interface for managing and interacting with The SaaS Company's cloud services, providing streamlined access to resources and operations."
  homepage "https://thesaas.company.io/docs"
  version "0.0.32"

  on_macos do
    on_intel do
      url "https://github.com/thesaas-company/cloud/releases/download/v0.0.32/cloud_Darwin_x86_64.tar.gz"
      sha256 "5f113fc89149b59243f80fcacd107258d7a195125e4522e26474bbab50fa1c54"

      def install
        bin.install "tfstudio"
      end
    end
    on_arm do
      url "https://github.com/thesaas-company/cloud/releases/download/v0.0.32/cloud_Darwin_arm64.tar.gz"
      sha256 "4fbceef8c0a60d5593709ece90fb33babd3a11fd9a9d32fd0ce1ebd9a295f35b"

      def install
        bin.install "tfstudio"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thesaas-company/cloud/releases/download/v0.0.32/cloud_Linux_x86_64.tar.gz"
        sha256 "3ac17189e7c8f66e1f5fecb569814f02ab1e2701564f9c4aeeeda3af9761008a"

        def install
          bin.install "tfstudio"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thesaas-company/cloud/releases/download/v0.0.32/cloud_Linux_arm64.tar.gz"
        sha256 "d4783da0cd481d220aaf33f40c2ad975618fffaf98c77a002aa8351c4813408f"

        def install
          bin.install "tfstudio"
        end
      end
    end
  end
end
