# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xray < Formula
  desc "xray is a command line tool to interact with databases."
  homepage "https://thesaas.company"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/thesaas-company/xray/releases/download/v0.0.1/xray_Darwin_x86_64.tar.gz"
      sha256 "06a8604ebf8644d14f6ed008f890e71f1ae82d932f97d97c8246b15edd56712d"

      def install
        bin.install "xray"
      end
    end
    on_arm do
      url "https://github.com/thesaas-company/xray/releases/download/v0.0.1/xray_Darwin_arm64.tar.gz"
      sha256 "5ee0ffcdffe082e5c20e6cfb5be2f26811740e739859ca1099715615793dc6d2"

      def install
        bin.install "xray"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thesaas-company/xray/releases/download/v0.0.1/xray_Linux_x86_64.tar.gz"
        sha256 "688456edd49ebba8be8fb876eceed9ccfda126f486a1ee24efc8026516c0eeb7"

        def install
          bin.install "xray"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thesaas-company/xray/releases/download/v0.0.1/xray_Linux_arm64.tar.gz"
        sha256 "8106ef99c32dd7c34e1d40596cda086aed037bd195689bd7fdf41b77b73cdc01"

        def install
          bin.install "xray"
        end
      end
    end
  end
end
